# Generated by Django 3.0.2 on 2020-02-08 09:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_feedpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
