# Generated by Django 3.0.2 on 2020-02-09 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_auto_20200209_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedpost',
            name='subtitle',
            field=models.TextField(null=True),
        ),
    ]
